version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/application"
    schedule:
      interval: "weekly"
    ignore:
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
